spring:
  datasource:
    url: jdbc:h2:mem:credit_app_system_db
    username: user
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
#      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
